# Generated by Django 5.1.1 on 2024-09-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_devolver',
            new_name='fecha_devolucion',
        ),
    ]
