# Generated by Django 5.1.1 on 2024-09-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_rename_fecha_devolver_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('en_proceso', 'En Proceso'), ('prestado', 'Prestado'), ('devuelto', 'Devuelto')], default='solicitado', max_length=20),
        ),
    ]
